[tool.ruff]
target-version="py312"
line-length = 80
indent-width = 4
ignore = ["F401"]

[tool.ruff.format]

quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
 norecursedirs = ["alpha-zero-general"]
 pythonpath = "."
 testpaths = ["tests"]
log_cli = true
log_cli_level = "DEBUG"
addopts = "-vv"

[tool.vscode]
python.envFile = ".env"