[tool.ruff]
target-version="py39"
line-length = 80
indent-width = 4

[tool.ruff.format]

quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
norecursedirs = ["alpha-zero-general"]
pythonpath = "."
testpaths = ["tests",]
log_cli = true
log_level = "DEBUG"
addopts = "-vv"
