hydra:
  run:
    dir: "./logs/${now:%Y-%m%d-%H%M-%S}/"
csv_path: /Users/takeruito/work/AlphaSymbol/data/prfndim/d3-a5-c3-r5-generated.csv
accelerator: mps # gpu for Linux, mps for Mac
max_epochs: 2
learning_rate: "8*10**(-5)"
batch_size: 32
transformer:
  d_model: 512
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
